# Generated by Django 3.1.3 on 2021-03-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0004_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='cover',
            field=models.TextField(blank=True, max_length=260, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='cvs'),
        ),
        migrations.AlterField(
            model_name='person',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
