# Generated by Django 3.1.3 on 2021-03-29 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0009_auto_20210329_1925'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
